### ISSUE TITLE
Do the training scripts provide the hyper-parameters used to train the model in your paper?

### ISSUE THREAD

**Issue by YHQpkueecs** [Shalev-Lifshitz/STEVE-1#10]
Hello! I would like to ask, if we download all the required data (8.x,9.x,10.x), can we reproduce Steve-1 with hyper-parameters in the current released training scripts?

**Comment by Shalev-Lifshitz** [comment]
Hi there, as specified in Appendix C of the paper, most of the data for STEVE-1 comes from the 8.x,9.x,10.x data, but, we also included ~15M frames of VPT-generated data to train STEVE-1 (data generation scripts are in the repo). I would recommend training on the 8.x,9.x,10.x data as its the easiest to download/generate and you can get performance from it.

**Comment by KarolisRam** [comment]
Hi Shalev,

Did you use `--gradient_accumulation_steps 4` for training? Just double checking, since that one is not included in the table in the paper. Also, the `n_frames` don't match between the script and the table:

<img width="714" height="383" alt="Image" src="https://github.com/user-attachments/assets/e426754a-0368-41ba-bde5-50118f081fe1" />
