### ISSUE TITLE
Some questions of interest regarding the details of Prior training.

### ISSUE THREAD

**Issue by Zhoues** [Shalev-Lifshitz/STEVE-1#12]
In the Appendix D.2 section of the paper, the Prior Training section, I understood how Steve-1 collected text-video pairs for training the Prior. I am particularly interested in two points 😄 :
1. I am curious about how I can obtain the 2000 hand-labeled text examples/10000 augmented text examples because I want to try to have the Steve-1 Agent perform some tasks that are trained but not among those 11 tasks.
2. How can I use mineclip to retrieve videos, is there a script for this? I am curious about how the `offset` operation mentioned in the paper is smoothly implemented.

Looking forward to your reply ❤️ @Shalev-Lifshitz

**Comment by Shalev-Lifshitz** [comment]
Hi there, apologies for the late reply! Unfortunately, the only data we have is what is downloaded here https://github.com/Shalev-Lifshitz/STEVE-1/blob/main/download_weights.sh#L22C1-L22C102, which only has the embeddings, rather than the 16-frame videos themselves.

Regarding retrieval with MineCLIP, we did not release a script for this. But you can make use of the [FAISS](https://github.com/facebookresearch/faiss) library. You would need to compute the MineCLIP embeddings for each frame in whatever dataset you are searching over, and then use FAISS to retrieve the most similar embeddings (see FAISS documentation).

**Comment by artbelyaev0** [comment]
> In the Appendix D.2 section of the paper, the Prior Training section, I understood how Steve-1 collected text-video pairs for training the Prior. I am particularly interested in two points 😄 :
> 
> 1. I am curious about how I can obtain the 2000 hand-labeled text examples/10000 augmented text examples because I want to try to have the Steve-1 Agent perform some tasks that are trained but not among those 11 tasks.
> 2. How can I use mineclip to retrieve videos, is there a script for this? I am curious about how the `offset` operation mentioned in the paper is smoothly implemented.
> 
> Looking forward to your reply ❤️ @Shalev-Lifshitz

Hello! Did you get a dataset for training custom VAE ? May be you can share it please ?
