### ISSUE TITLE
1_gen_paper_videos.sh generates 1 video for dig, then kills program.

### ISSUE THREAD

**Issue by TimeLordRaps** [Shalev-Lifshitz/STEVE-1#2]
```
Updating count for dirt from 3 to 4
100%|███████████████████████████████████████████████████████████████████████████████| 3000/3000 [03:11<00:00, 15.66it/s]
Programmatic Evaluation Results:
log: 0
dirt: 4
seed: 0
travel_dist: 1.25625379491464

Generating video for text prompt with name: dirt
Loading MineClip...
Loading agent with cond_scale 6.0...
Loading MineRL...
Starting new env...
<frozen runpy>:128: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
Killed
```

Wondering if you have any idea what is going on. I have had success running interactively and with custom prompt, so I believe it has something to do more with the prompts, or the way the reloading of the agent. I have a total of 4gb of vram, but again I am able to run the model for custom prompts and interactively.

**Comment by Shalev-Lifshitz** [comment]
Ah yes, thanks for asking. I believe this is an issue with MineRL. Specifically, if we create multiple MineRL environments one after another, sometimes the program dies for some reason (not sure exactly why as its internal to MineRL). 

Usually I'm able to create multiple environments before experiencing this error, but this may be because I have lots of RAM. In this case, a simple solution would be to just not recompute videos that have already been created and run the python code in a loop inside of a bash script.

I can push code for not recomputing already created videos tomorrow, as well as a simple script that will run the code to generate videos in an infinite loop.

**Comment by TimeLordRaps** [comment]
Thanks that seems like it would remedy the situation,  I'll check when I get the chance.

**Comment by Shalev-Lifshitz** [comment]
Just pushed an update that should fix this problem. Also, it will automatically end once all videos are generated so you don't need to manually monitor it.
