### ISSUE TITLE
Reproducing environment

### ISSUE THREAD

**Issue by juliusfrost** [Shalev-Lifshitz/STEVE-1#6]
Hello,

I'm trying to install dependencies for this but I'm having some trouble with minerl. I installed it before last year but haven't been able to get it working as of late. Could you verify this?
Also, if possible, could you provide a [Dockerfile](https://docs.docker.com/engine/reference/builder/) that installs all the dependencies? This would make reproducing your work much easier and a very much needed contribution to RL for Minecraft.

Thanks,

**Comment by Shalev-Lifshitz** [comment]
Hi there, are you using the `v1.0.1` version of MineRL specified in the README? (Full command is `pip install git+https://github.com/minerllabs/minerl@v1.0.1`). I ask this question because MineRL was apparently broken for a while until recently and this `v1.0.1` version should fix those issues. Using the mentioned command, I was able to install MineRL in a completely fresh python environment just last week so the installation should work.

Also, if you are installing all the dependencies mentioned in the README, I recommend running the installation commands in the listed order, since there are some clashes between MineRL and MineDojo and the order should take care of that.

Regarding a Dockerfile, you might be able to find one on the MineRL website/discord but unfortunately I don't have access to one. I would recommend running without docker if that's possible for you.
